name: Find Replace Var
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "$pia_lang['Device_"
          replace: "$pia_lang['DEV_"
          regex: false
          exclude: "find_replace.yml"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Automated find and replace"

      - name: Push Changes to Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin next_update
